# Model 2: Refund Risk Probability
Predict whether an ordered item will be refunded (binary classification).

In [65]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report, roc_auc_score
from statsmodels.stats.outliers_influence import variance_inflation_factor
import joblib

# Uploading the required files to colab storage

In [66]:
from google.colab import files
files.upload()

ModuleNotFoundError: No module named 'google.colab'

# Load raw data

In [67]:
''' for notebook

order_items = pd.read_csv(r'C:\Users\sneha\Projects\Internship\Project_1\shreesneha056@gmail.com\e-commerce_project\data\order_items.csv', parse_dates=['created_at'])
order_item_refunds = pd.read_csv(r'C:\Users\sneha\Projects\Internship\Project_1\shreesneha056@gmail.com\e-commerce_project\data\order_item_refunds.csv', parse_dates=['created_at'])
products = pd.read_csv(r'C:\Users\sneha\Projects\Internship\Project_1\shreesneha056@gmail.com\e-commerce_project\data\products.csv')
orders = pd.read_csv(r'C:\Users\sneha\Projects\Internship\Project_1\shreesneha056@gmail.com\e-commerce_project\data\orders.csv', parse_dates=['created_at'])

SyntaxError: incomplete input (2913356995.py, line 1)

In [68]:
order_items = pd.read_csv('order_items.csv', parse_dates=['created_at'])
order_item_refunds = pd.read_csv('order_item_refunds.csv', parse_dates=['created_at'])
products = pd.read_csv('products.csv')
orders = pd.read_csv('orders.csv', parse_dates=['created_at'])

FileNotFoundError: [Errno 2] No such file or directory: 'order_items.csv'

In [ ]:
order_items.head(3)

,order_item_id,created_at,order_id,product_id,is_primary_item,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,1,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,2,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,3,1,1,49.99,19.49

In [69]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 40025 entries, 0 to 40024
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    40025 non-null  int64
 1   created_at       40025 non-null  datetime64[us]
 2   order_id         40025 non-null  int64
 3   product_id       40025 non-null  int64
 4   is_primary_item  40025 non-null  int64
 5   price_usd        40025 non-null  float64
 6   cogs_usd         40025 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(4)
memory usage: 2.1 MB

In [70]:
order_item_refunds.head(3)

,order_item_refund_id,created_at,order_item_id,order_id,refund_amount_usd
0,1,2012-04-06 11:32:43,57,57,49.99
1,2,2012-04-13 01:09:43,74,74,49.99
2,3,2012-04-15 07:03:48,71,71,49.99

In [71]:
order_item_refunds.info()

<class 'pandas.DataFrame'>
RangeIndex: 1731 entries, 0 to 1730
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_item_refund_id  1731 non-null   int64
 1   created_at            1731 non-null   datetime64[us]
 2   order_item_id         1731 non-null   int64
 3   order_id              1731 non-null   int64
 4   refund_amount_usd     1731 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(3)
memory usage: 67.7 KB

# Data cleaning

In [72]:
order_items.isnull().sum()

order_item_id      0
created_at         0
order_id           0
product_id         0
is_primary_item    0
price_usd          0
cogs_usd           0
dtype: int64

In [73]:
order_items.duplicated().sum()

np.int64(0)

In [74]:
order_item_refunds.isnull().sum()

order_item_refund_id    0
created_at              0
order_item_id           0
order_id                0
refund_amount_usd       0
dtype: int64

In [75]:
order_item_refunds.duplicated().sum()

np.int64(0)

# Build the target variable
An order item is "refunded" if it has at least one matching row in order_item_refunds.
We dedupe refunds to 1 row per order_item_id before merging, to avoid fan-out.

In [76]:
refunds_agg = order_item_refunds.pivot_table(index='order_item_id',aggfunc='size').reset_index().rename(columns={0:'num_refund_records'})

In [77]:
refunds_agg.head(3)

   order_item_id  num_refund_records
0             57                   1
1             71                   1
2             74                   1

In [78]:
#refunds_agg = order_item_refunds.groupby('order_item_id').size().reset_index(name='num_refund_records')

In [79]:
#refunds_agg.head(3)

In [80]:
data = order_items.merge(refunds_agg, on='order_item_id', how='left')

In [81]:
data['num_refund_records'] = data['num_refund_records'].fillna(0)

In [82]:
data['refunded'] = np.where(data['num_refund_records'] > 0, 1, 0)

In [83]:
data['refunded'].value_counts()

refunded
0    38294
1     1731
Name: count, dtype: int64

In [84]:
data['refunded'].value_counts(normalize=True)

refunded
0    0.956752
1    0.043248
Name: proportion, dtype: float64

## Class imbalance -- addressed explicitly (same as Model 1)
Refund rate is typically low. We handle this via class_weight='balanced' /
scale_pos_weight, stratified train/test split, and threshold tuning below --
not just accuracy, since a "never refund" model would score misleadingly high.

In [85]:
data = data.merge(products, on='product_id', how='left')

In [86]:
data.head(3)

,order_item_id,created_at_x,order_id,product_id,is_primary_item,price_usd,cogs_usd,num_refund_records,refunded,created_at_y,product_name
0,1,2012-03-19 10:42:46,1,1,1,49.99,19.49,0.0,0,2012-03-19 08:00:00,The Original Mr. Fuzzy
1,2,2012-03-19 19:27:37,2,1,1,49.99,19.49,0.0,0,2012-03-19 08:00:00,The Original Mr. Fuzzy
2,3,2012-03-20 06:44:45,3,1,1,49.99,19.49,0.0,0,2012-03-19 08:00:00,The Original Mr. Fuzzy

In [87]:
orders.head(3)

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,20,20,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,104,104,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,147,147,1,1,49.99,19.49

In [88]:
orders.columns

Index(['order_id', 'created_at', 'website_session_id', 'user_id',
       'primary_product_id', 'items_purchased', 'price_usd', 'cogs_usd'],
      dtype='str')

In [89]:
data = data.merge(
    orders[['order_id', 'price_usd']],
    on='order_id',
    how='left',
    suffixes=('', '_order')
)

In [57]:
data.head(3)

,order_item_id,created_at_x,order_id,product_id,is_primary_item,price_usd,cogs_usd,num_refund_records,refunded,created_at_y,product_name,price_usd_order
0,1,2012-03-19 10:42:46,1,1,1,49.99,19.49,0.0,0,2012-03-19 08:00:00,The Original Mr. Fuzzy,49.99
1,2,2012-03-19 19:27:37,2,1,1,49.99,19.49,0.0,0,2012-03-19 08:00:00,The Original Mr. Fuzzy,49.99
2,3,2012-03-20 06:44:45,3,1,1,49.99,19.49,0.0,0,2012-03-19 08:00:00,The Original Mr. Fuzzy,49.99

In [94]:
check = data['price_usd'] == data['price_usd_order']

In [95]:
check.value_counts()

True     24601
False    15424
Name: count, dtype: int64

In [96]:
data['month'] = data['created_at_x'].dt.month
data['dayofweek'] = data['created_at_x'].dt.dayofweek

In [97]:
data.columns

Index(['order_item_id', 'created_at_x', 'order_id', 'product_id',
       'is_primary_item', 'price_usd', 'cogs_usd', 'num_refund_records',
       'refunded', 'created_at_y', 'product_name', 'price_usd_order', 'month',
       'dayofweek'],
      dtype='str')

In [98]:
feature_cols = ['is_primary_item', 'price_usd', 'cogs_usd',
        'product_id', 'price_usd_order', 'month',
       'dayofweek']
target = ['refunded']

In [99]:
X = data[['is_primary_item', 'price_usd', 'cogs_usd',
        'product_id', 'price_usd_order', 'month',
       'dayofweek']]

In [100]:
data.columns

Index(['order_item_id', 'created_at_x', 'order_id', 'product_id',
       'is_primary_item', 'price_usd', 'cogs_usd', 'num_refund_records',
       'refunded', 'created_at_y', 'product_name', 'price_usd_order', 'month',
       'dayofweek'],
      dtype='str')

In [101]:
y = data['refunded']

In [102]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123, stratify=y)

# Encode features for sklearn models

In [36]:
X_train.shape, X_test.shape

((32020, 7), (8005, 7))

# Class imbalance ratio (for XGBoost's scale_pos_weight)

In [30]:
neg, pos = np.bincount(y_train)
imbalance_ratio = neg / pos

# Model comparison

# Model A: Logistic Regression (class_weight='balanced')

In [31]:
par_grid_lr = {'C': [0.01, 0.1, 1]}
grid_lr = GridSearchCV(LogisticRegression(max_iter=500, class_weight='balanced'),
                        param_grid=par_grid_lr, cv=3, scoring='roc_auc', n_jobs=-1)
grid_lr = grid_lr.fit(X_train, y_train)

In [32]:
grid_lr.best_params_, grid_lr.best_score_

({'C': 1}, np.float64(0.5928873449667368))

In [ ]:
lr = grid_lr.best_estimator_

In [ ]:
print(classification_report(y_train, lr.predict(X_train)))

              precision    recall  f1-score   support

           0       0.98      0.28      0.44     30635
           1       0.05      0.89      0.10      1385

    accuracy                           0.31     32020
   macro avg       0.52      0.58      0.27     32020
weighted avg       0.94      0.31      0.42     32020

In [ ]:
print(classification_report(y_test, lr.predict(X_test)))

              precision    recall  f1-score   support

           0       0.98      0.27      0.43      7659
           1       0.05      0.90      0.10       346

    accuracy                           0.30      8005
   macro avg       0.52      0.58      0.26      8005
weighted avg       0.94      0.30      0.41      8005

# Model B: Random Forest (class_weight='balanced')

In [ ]:
par_grid_rf = {'n_estimators': [100], 'max_depth': [8]}
grid_rf = GridSearchCV(RandomForestClassifier(n_jobs=-1, random_state=123, class_weight='balanced'),
                        param_grid=par_grid_rf, cv=3, scoring='roc_auc', n_jobs=-1)
grid_rf = grid_rf.fit(X_train, y_train)

In [ ]:
grid_rf.best_params_, grid_rf.best_score_

({'max_depth': 8, 'n_estimators': 100}, np.float64(0.6205211662653211))

In [ ]:
rf = grid_rf.best_estimator_

In [ ]:
print(classification_report(y_train, rf.predict(X_train)))
print(classification_report(y_test, rf.predict(X_test)))

              precision    recall  f1-score   support

           0       0.98      0.61      0.75     30635
           1       0.07      0.66      0.13      1385

    accuracy                           0.61     32020
   macro avg       0.52      0.63      0.44     32020
weighted avg       0.94      0.61      0.72     32020

              precision    recall  f1-score   support

           0       0.97      0.60      0.74      7659
           1       0.06      0.60      0.12       346

    accuracy                           0.60      8005
   macro avg       0.52      0.60      0.43      8005
weighted avg       0.93      0.60      0.72      8005

# Model C: XGBoost (scale_pos_weight fixed to imbalance ratio)

In [ ]:
par_grid_xgb = {'n_estimators': [100], 'max_depth': [3, 5], 'learning_rate': [0.05, 0.1]}
grid_xgb = GridSearchCV(XGBClassifier(eval_metric='logloss', random_state=123, scale_pos_weight=imbalance_ratio),
                         param_grid=par_grid_xgb, cv=3, scoring='roc_auc', n_jobs=-1)
grid_xgb = grid_xgb.fit(X_train, y_train)

In [ ]:
grid_xgb.best_params_, grid_xgb.best_score_

({'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 100},
 np.float64(0.6361637435342268))

In [ ]:
xgb = grid_xgb.best_estimator_

In [ ]:
print(classification_report(y_train, xgb.predict(X_train)))
print(classification_report(y_test, xgb.predict(X_test)))

              precision    recall  f1-score   support

           0       0.97      0.67      0.79     30635
           1       0.07      0.55      0.12      1385

    accuracy                           0.66     32020
   macro avg       0.52      0.61      0.46     32020
weighted avg       0.93      0.66      0.76     32020

              precision    recall  f1-score   support

           0       0.97      0.67      0.79      7659
           1       0.07      0.55      0.13       346

    accuracy                           0.67      8005
   macro avg       0.52      0.61      0.46      8005
weighted avg       0.93      0.67      0.77      8005

# Model D: LightGBM (class_weight='balanced')

In [33]:
par_grid_lgb = {'n_estimators': [100], 'max_depth': [3, 5], 'learning_rate': [0.05, 0.1]}
grid_lgb = GridSearchCV(LGBMClassifier(random_state=123, verbose=-1, class_weight='balanced'),
                         param_grid=par_grid_lgb, cv=3, scoring='roc_auc', n_jobs=-1)
grid_lgb = grid_lgb.fit(X_train, y_train)

In [34]:
grid_lgb.best_params_, grid_lgb.best_score_

({'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 100},
 np.float64(0.6368025901361105))

In [35]:
lgbm = grid_lgb.best_estimator_

In [36]:
print(classification_report(y_train, lgbm.predict(X_train)))
print(classification_report(y_test, lgbm.predict(X_test)))

              precision    recall  f1-score   support

           0       0.97      0.67      0.79     30635
           1       0.07      0.55      0.12      1385

    accuracy                           0.66     32020
   macro avg       0.52      0.61      0.46     32020
weighted avg       0.93      0.66      0.76     32020

              precision    recall  f1-score   support

           0       0.97      0.67      0.79      7659
           1       0.07      0.55      0.13       346

    accuracy                           0.67      8005
   macro avg       0.52      0.61      0.46      8005
weighted avg       0.93      0.67      0.77      8005

# Compare all models on ROC-AUC

In [ ]:
score = pd.DataFrame([grid_lr.best_score_, grid_rf.best_score_, grid_xgb.best_score_, grid_lgb.best_score_])
name = pd.DataFrame(['logistic_regression', 'random_forest', 'xgboost', 'lightgbm'])

In [ ]:
best_score = pd.concat([name, score], axis=1)
best_score.columns = ['model', 'roc_auc']
best_score.sort_values('roc_auc', ascending=False)

                 model   roc_auc
3             lightgbm  0.636803
2              xgboost  0.636164
1        random_forest  0.620521
0  logistic_regression  0.592889

# Threshold tuning on best model

In [37]:
best_proba = lgbm.predict_proba(X_test)[:, 1]

for t in [0.3, 0.4, 0.5, 0.6, 0.7]:
    print(f"for Threshold = {t}")
    pred = np.where(best_proba >= t, 1, 0)
    print(classification_report(y_test, pred))

for Threshold = 0.3
              precision    recall  f1-score   support

           0       0.99      0.12      0.22      7659
           1       0.05      0.97      0.09       346

    accuracy                           0.16      8005
   macro avg       0.52      0.55      0.15      8005
weighted avg       0.95      0.16      0.21      8005

for Threshold = 0.4
              precision    recall  f1-score   support

           0       0.98      0.26      0.41      7659
           1       0.05      0.90      0.10       346

    accuracy                           0.29      8005
   macro avg       0.52      0.58      0.26      8005
weighted avg       0.94      0.29      0.40      8005

for Threshold = 0.5
              precision    recall  f1-score   support

           0       0.97      0.67      0.79      7659
           1       0.07      0.55      0.13       346

    accuracy                           0.67      8005
   macro avg       0.52      0.61      0.46      8005
weighted avg       0.93      0.67      0.77      8005

for Threshold = 0.6
              precision    recall  f1-score   support

           0       0.96      0.88      0.92      7659
           1       0.10      0.29      0.15       346

    accuracy                           0.86      8005
   macro avg       0.53      0.58      0.53      8005
weighted avg       0.93      0.86      0.89      8005

for Threshold = 0.7
              precision    recall  f1-score   support

           0       0.96      1.00      0.98      7659
           1       0.20      0.00      0.01       346

    accuracy                           0.96      8005
   macro avg       0.58      0.50      0.49      8005
weighted avg       0.92      0.96      0.94      8005

# best_threshold = 0.4

In [38]:
best_threshold = 0.4
final_model = {'model': lgbm, 'threshold': best_threshold}

In [41]:
''' for notebook

joblib.dump(r'C:\Users\sneha\Projects\Internship\e-commerce_project1\eda\final_model.pkl', filename= 'refund_model_final_lgbm')

['refund_model_final_lgbm']

In [42]:
joblib.dump(final_model, 'refund_model_final_lgbm.pkl')

['refund_model_final_lgbm.pkl']

# End